// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import SearchSortController from "./search_sort_controller"
application.register("search-sort", SearchSortController)

import SortController from "./sort_controller"
application.register("sort", SortController)
